-   repo: https://github.com/troian/pre-commit-golang
    sha: HEAD
    hooks:
    -   id: go-fmt
#    -   id: go-build
#    -   id: go-metalinter
#        args:
#        - --exclude=corefoundation.go
#        - --deadline=60s
#        - --vendor
#        - --cyclo-over=20
#        - --dupl-threshold=100
#        - --disable=gotype
